# Generated by Django 5.1.4 on 2024-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
