# Generated by Django 5.1.4 on 2024-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
