# Generated by Django 5.1.4 on 2024-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_profile_pic.jpg",
                null=True,
                upload_to="profile_pictures",
            ),
        ),
    ]
